(function(){
  const palette=['#d92d20','#f79009','#fdb022','#12b76a','#2e90fa','#7f56d9','#0f766e','#475467'];
  function setup(canvas){ const dpr=window.devicePixelRatio||1, box=canvas.getBoundingClientRect(); canvas.width=Math.max(320,box.width)*dpr; canvas.height=Math.max(220,box.height)*dpr; const c=canvas.getContext('2d'); c.setTransform(dpr,0,0,dpr,0,0); return {c,w:Math.max(320,box.width),h:Math.max(220,box.height)}; }
  function clear(c,w,h){c.clearRect(0,0,w,h);c.font='12px Segoe UI,Arial';c.fillStyle='#667085';}
  function axes(c,w,h,max){const l=44,r=18,t=18,b=36; c.strokeStyle='#eaecf0';c.lineWidth=1; for(let i=0;i<=4;i++){let y=t+(h-t-b)*i/4;c.beginPath();c.moveTo(l,y);c.lineTo(w-r,y);c.stroke();let v=Math.round(max*(4-i)/4);c.fillText(v,6,y+4);} return {l,r,t,b,pw:w-l-r,ph:h-t-b};}
  window.HospitalCharts={
    line(canvas,labels,series){let {c,w,h}=setup(canvas);clear(c,w,h);let max=Math.max(1,...series.flatMap(s=>s.values));let a=axes(c,w,h,max);series.forEach((s,si)=>{c.strokeStyle=palette[si%palette.length];c.fillStyle=palette[si%palette.length];c.lineWidth=2.5;c.beginPath();s.values.forEach((v,i)=>{let x=a.l+(labels.length<=1?0:a.pw*i/(labels.length-1)),y=a.t+a.ph*(1-v/max);if(i===0)c.moveTo(x,y);else c.lineTo(x,y);});c.stroke();s.values.forEach((v,i)=>{let x=a.l+(labels.length<=1?0:a.pw*i/(labels.length-1)),y=a.t+a.ph*(1-v/max);c.beginPath();c.arc(x,y,3,0,Math.PI*2);c.fill();});}); let step=Math.max(1,Math.ceil(labels.length/8));labels.forEach((v,i)=>{if(i%step===0){let x=a.l+(labels.length<=1?0:a.pw*i/(labels.length-1));c.fillStyle='#667085';c.fillText(v,x-12,h-12);}});},
    bars(canvas,labels,values){let {c,w,h}=setup(canvas);clear(c,w,h);let max=Math.max(1,...values),a=axes(c,w,h,max),slot=a.pw/Math.max(1,labels.length),bw=Math.max(8,slot*.55);values.forEach((v,i)=>{let x=a.l+slot*i+(slot-bw)/2,y=a.t+a.ph*(1-v/max);c.fillStyle=palette[i%palette.length];c.fillRect(x,y,bw,a.t+a.ph-y);});let step=Math.max(1,Math.ceil(labels.length/7));labels.forEach((v,i)=>{if(i%step===0){c.fillStyle='#667085';c.fillText(v,a.l+slot*i,h-12);}});},
    doughnut(canvas,labels,values){let {c,w,h}=setup(canvas);clear(c,w,h);let total=values.reduce((a,b)=>a+b,0)||1,cx=w*.34,cy=h*.5,r=Math.min(w,h)*.28,start=-Math.PI/2;values.forEach((v,i)=>{let ang=Math.PI*2*v/total;c.beginPath();c.strokeStyle=palette[i%palette.length];c.lineWidth=Math.max(22,r*.34);c.arc(cx,cy,r,start,start+ang);c.stroke();start+=ang;});c.textAlign='center';c.fillStyle='#101828';c.font='700 24px Segoe UI';c.fillText(values.reduce((a,b)=>a+b,0),cx,cy+5);c.font='12px Segoe UI';c.fillStyle='#667085';c.fillText('classificações',cx,cy+24);c.textAlign='left';labels.forEach((v,i)=>{let y=24+i*25;c.fillStyle=palette[i%palette.length];c.fillRect(w*.62,y-9,10,10);c.fillStyle='#344054';c.fillText(v+' ('+values[i]+')',w*.62+17,y);});}
  };
})();
